import matplotlib.pyplot as plt

import pandas as pd


# the below method plot_JSSP_Gantt was mostly generated by AI with significant edits
def plot_JSSP_Gantt(
    reconstruction: list[
        list[
            tuple[int, int, int, int]
        ]
    ],
    num_jobs: int,
    num_machines: int,
    save_path: str | None = None,
    show: bool = False
):

    # Create a DataFrame to hold the Gantt chart data

    gantt_data = []

    for machine in range(
        num_machines
    ):

        for job_step in reconstruction[
            machine
        ]:

            (
                job,
                machine_num,
                start_time,
                duration
            ) = job_step

            if job != -1:

                gantt_data.append({

                    'Job':
                        f'Job {job}',

                    'Machine':
                        f'Machine {machine_num}',

                    'Start':
                        start_time,

                    'Duration':
                        duration
                })

    df = pd.DataFrame(
        gantt_data
    )

    # Create the Gantt chart
    # NOTE It would be nice to sort the key by job number

    fig, ax = plt.subplots(
        figsize=(10, 6)
    )

    job_colors = (
        plt.colormaps[
            'turbo'
        ].resampled(
            num_jobs
        )
    )

    # job_colors = plt.colormaps['tab20c'].resampled(num_jobs)

    job_added_to_key = [
        bool(False)
        for _ in range(num_jobs)
    ]

    for idx, row in df.iterrows():

        job_number = int(
            row['Job'].split()[-1]
        )

        label = (
            row['Job']
            if not job_added_to_key[
                job_number
            ]
            else "_nolegend_"
        )

        ax.barh(
            row['Machine'],
            row['Duration'],
            left=row['Start'],
            color=job_colors(
                job_number
            ),
            label=label,
        )

        job_added_to_key[
            job_number
        ] = True

    ax.set_xlabel(
        'Time'
    )

    ax.set_ylabel(
        'Machines'
    )

    ax.set_title(
        'Gantt Chart for JSSP'
    )

    ax.legend(
        loc='upper right'
    )

    if save_path is not None:

        plt.savefig(
            save_path,
            bbox_inches='tight'
        )

    if show is True:
        plt.show()

    plt.close(fig)